# Generated by Django 4.2.7 on 2023-11-16 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="Address",
            new_name="address",
        ),
    ]
