# Generated by Django 4.2.7 on 2023-11-17 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_user_created_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="created_at",
            new_name="date",
        ),
    ]
